### ISSUE TITLE
Error logging support and view UI

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-console#327] opened 2020-01-20 01:53 UTC
Many users complain about the display of error messages as snackbars. Snackbars stack like burgers when there are many error messages which makes users very cumbersome. Furthermore, error messages are usually cryptic to normal users only to make confusing them.

We are going to store error logs and make snackbar error messages neater.

* When there is an error response, store (append) the information on localStorage (or sessionStorage) with a key like 'clientLog'.
  - Needed information: timestamp, request url, request method, status code, error title, detailed error message before parsing by PainKiller or something else.
  - Limit the size of the logs. For example, 10 kiB? (localStorage and sessionsStorage size limit is 5 MiB).
  - Logs should be cleared when user logged out.
* Stored logs can be display by a button.
  - Where to put the button?
  - Any suggestions?
* How to change current snackbar notification?
  - Keep them?
  - Replace them with traffic light like indicator? (red on error, green on success?)
  - Any suggestions?

**Comment by achimnol** [comment] 2020-01-21 08:47
This will be backed by [the server-side persistent error logging subsystem](lablup/backend.ai#110).

**Comment by achimnol** [comment] 2020-01-21 09:08
Also please take advantage of Sentry-like global exception handlers to acutally catch arbitrary exceptions in the javascript code. Refer the Sentry's plugin implementation.

**Comment by achimnol** [comment] 2020-01-21 09:13
We need an extra caution to keep *connection* errors when the browser cannot access the manager (e.g., the error logging API is not accessible). In this case, we may need to complement the implementation with local storage, but in a not-too-complicated way. Probably keeping only the last connection error would suffice.

**Comment by inureyes** [comment] 2020-02-29 03:00
Duplicate of #320

**Closed** 2020-02-29 02:59 UTC
Labels: UI / UX, duplicate, enhancement
